services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ricsanfre
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  backend-demo-app:
    container_name: backend-demo-app
    image: ricsanfre/spring-boot-demo-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    # Not needed to pass JDBC URL because set environment variable.
    # command:
    #  - --spring.datasource.url=$POSTGRES_URL
  react-frontend-demo-app:
    container_name: react-frontend-demo-app
    image: ricsanfre/spring-boot-demo-react
    build:
      context: frontend/react
      args:
        - BACKEND_URL=http://localhost:8080
    depends_on:
      - backend-demo-app
    ports:
      - "3000:5173"
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db:
