services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ricsanfre
      POSTGRES_PASSWORD: s1cret0
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  demo-app:
    container_name: demo-app
    image: ricsanfre/spring-boot-example
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    # Not needed to pass JDBC URL because set environment variable.
    # command:
    #  - --spring.datasource.url=$POSTGRES_URL
networks:
  db:
    driver: bridge
volumes:
  db:
