name: CD - Deploy React Frontend
on:
  # Launch workflow manually
  workflow_dispatch:
  # Launch workflow on push on master
  push:
    branches:
      - master
    paths:
      - frontend/react/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images.
        uses: docker/build-push-action@v2
        with:
          context: frontend/react
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ricsanfre/spring-boot-demo-react:latest