name: CD - Deploy React Frontend
on:
  # Launch workflow manually
  workflow_dispatch:
  # Launch workflow on push on master
  push:
    branches:
      - master
    paths:
      - frontend/react/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images.
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/react
          file: ./frontend/react/Dockerfile
          build-args: |
            BACKEND_URL=${{ secrets.EB_ENVIRONMENT_URL }}:8080
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ricsanfre/spring-boot-demo-react:latest